name: archify_app
description: Mobile app for Archify
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.1
  camera: ^0.12.0
  app_settings: ^7.0.0
  lucide_icons: ^0.257.0
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.4
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
